server {
    listen 80;
    server_name localhost;

    # Health check route for Azure
    location = /robots933456.txt {
        return 200 'Healthy\n';
        add_header Content-Type text/plain;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Add cache headers for static assets
    location /static {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}
