server {
    listen 80;
    server_name localhost;

    # Health check route for Azure
    location = /robots933456.txt {
        return 200 'Healthy\n';
        add_header Content-Type text/plain;
    }

    # Proxy API requests to backend
    location /api/ {
        proxy_pass https://pfe-backend-hac7djg2eubjbsar.canadacentral-01.azurewebsites.net;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Handle image requests
    location /uploads/ {
        proxy_pass https://pfe-backend-hac7djg2eubjbsar.canadacentral-01.azurewebsites.net;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        
        # Add CORS headers
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Add cache headers for static assets
    location /static {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}
